{
	"version": 1625230479,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/black_screen-sheet0.png",
		"images/logo_pajak-sheet0.png",
		"images/armature_jump_-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bg_game-sheet0.png",
		"images/judul_game-sheet0.png",
		"images/bg_level-sheet0.png",
		"images/shadeddark-sheet0.png",
		"images/shadeddark-sheet1.png",
		"images/paused1-sheet0.png",
		"images/petunjuk_text-sheet0.png",
		"images/glosarium_text-sheet0.png",
		"images/cooltext-sheet0.png",
		"images/cooltext2-sheet0.png",
		"images/questionmark-sheet0.png",
		"images/dictionary-sheet0.png",
		"images/brainstorm-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/kotak_judul_level-sheet0.png",
		"images/button_keluar-sheet0.png",
		"images/button_back_home-sheet0.png",
		"images/button_back_level-sheet0.png",
		"images/papan_glorasium-sheet0.png",
		"images/bg_glorasium-sheet0.png",
		"images/warning1-sheet0.png",
		"images/gembok-sheet0.png",
		"images/blue_button-sheet0.png",
		"images/pengertian_pajak-sheet0.png",
		"images/pengertian_sejarah_pajak-sheet0.png",
		"images/pengertian_konsep_pajak-sheet0.png",
		"images/pengertian_fungsi_pajak-sheet0.png",
		"images/pengertian_manfaat_pajak-sheet0.png",
		"images/bg_home-sheet0.png",
		"images/button_bulat_p-sheet0.png",
		"images/piggybank-sheet0.png",
		"images/coins-sheet0.png",
		"images/money-sheet0.png",
		"images/shiba-sheet0.png",
		"images/button_bulat-sheet0.png",
		"images/papan_tulis-sheet0.png",
		"images/button_hijau-sheet0.png",
		"images/checklist_selesai-sheet0.png",
		"images/icon_bendera-sheet0.png",
		"images/garuda-sheet0.png",
		"images/kerajaan_zaman_dulu-sheet0.png",
		"images/penjajahan_jaman_dulu-sheet0.png",
		"images/suasana_kemerdekaan_45-sheet0.png",
		"images/orde_baru-sheet0.png",
		"images/reformasi_gambar-sheet0.png",
		"images/gambar_antrian_bansos-sheet0.png",
		"images/gambar_antrian_bantuan-sheet0.png",
		"images/mengenalpajakpenghasilanuntukpebisnis-sheet0.png",
		"images/gambar_fungsi1-sheet0.png",
		"images/gambar_construcsi-sheet0.png",
		"images/gambar_perbaikanjalan-sheet0.png",
		"images/hudout-sheet0.png",
		"images/closed_x-sheet0.png",
		"images/black_home-sheet0.png",
		"images/bg_soal-sheet0.png",
		"images/button_jawaban-sheet0.png",
		"images/truflase-sheet0.png",
		"images/truflase-sheet1.png",
		"images/bintang-sheet0.png",
		"images/bintang-sheet1.png",
		"images/button_hijau_bulat-sheet0.png",
		"images/gambar_highscore-sheet0.png",
		"images/gambar_score_game-sheet0.png",
		"images/gui_skor-sheet0.png",
		"images/button_play_blue-sheet0.png",
		"media/555798__ddmyzik__positive-cartoon-loop.m4a",
		"media/555798__ddmyzik__positive-cartoon-loop.ogg",
		"media/101268__wouter-hisschemoller__klik.m4a",
		"media/101268__wouter-hisschemoller__klik.ogg",
		"media/kevin macleod carefree (online-audio-converter.com).m4a",
		"media/kevin macleod carefree (online-audio-converter.com).ogg",
		"media/pengertian pajak (online-audio-converter.com).m4a",
		"media/pengertian pajak (online-audio-converter.com).ogg",
		"media/fungsi pajak (online-audio-converter.com).m4a",
		"media/fungsi pajak (online-audio-converter.com).ogg",
		"media/konsep pajak (online-audio-converter.com).m4a",
		"media/konsep pajak (online-audio-converter.com).ogg",
		"media/manfaat pajak (online-audio-converter.com).m4a",
		"media/manfaat pajak (online-audio-converter.com).ogg",
		"media/sejarah pajak (online-audio-converter.com).m4a",
		"media/sejarah pajak (online-audio-converter.com).ogg",
		"media/puk (online-audio-converter.com).m4a",
		"media/puk (online-audio-converter.com).ogg",
		"media/bagimu negeri (1xlagu) vocal & teks (online-audio-converter.com).m4a",
		"media/bagimu negeri (1xlagu) vocal & teks (online-audio-converter.com).ogg",
		"media/garuda pancasilalirik+musik instrument (online-audio-converter.com).m4a",
		"media/garuda pancasilalirik+musik instrument (online-audio-converter.com).ogg",
		"media/[karaoke] a. simanjuntak - bangun pemudi-pemuda +lirik lagu [piano] (online-audio-converter.com).m4a",
		"media/[karaoke] a. simanjuntak - bangun pemudi-pemuda +lirik lagu [piano] (online-audio-converter.com).ogg",
		"media/[karaoke] r. soerardjo - dari sabang sampai merauke +lirik lagu [piano] (online-audio-converter.com).m4a",
		"media/[karaoke] r. soerardjo - dari sabang sampai merauke +lirik lagu [piano] (online-audio-converter.com).ogg",
		"media/karaoke indonesia pusaka cipt. ismail marzuki (online-audio-converter.com).m4a",
		"media/karaoke indonesia pusaka cipt. ismail marzuki (online-audio-converter.com).ogg",
		"media/that positive feeling 5 (online-audio-converter.com).m4a",
		"media/that positive feeling 5 (online-audio-converter.com).ogg",
		"media/star (online-audio-converter.com).m4a",
		"media/star (online-audio-converter.com).ogg",
		"media/tungg (online-audio-converter.com).m4a",
		"media/tungg (online-audio-converter.com).ogg",
		"media/ting sound effect (online-audio-converter.com).m4a",
		"media/ting sound effect (online-audio-converter.com).ogg",
		"media/applause.ogg",
		"media/applause (online-audio-converter.com).m4a",
		"media/applause (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"soal.txt"
	]
}